services:
  postgres:
    image: postgres:16-alpine
    env_file:
      .env
    environment:
      POSTGRES_DB: scrapper
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d scrapper"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  scrapper:
    build:
      context: scrapper
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      bot:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgres:5432
      BOT_URL: http://bot:8080
    healthcheck:
      test: "curl -f http://localhost:8081/actuator/health"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SCRAPPER_URL: http://scrapper:8081
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.33
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      .env
    environment:
      POSTGRES_DB: scrapper
    command:
      - --searchPath=/changesets
      - --changelog-file=master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/scrapper
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    volumes:
      - ./migrations:/changesets


volumes:
  db-data: